### ISSUE TITLE
Greetings Mr.Sebastian

### ISSUE THREAD

**Issue by Amatsuknight** [sebastian-heinz/mho_launcher#2]
I am contacting you to request that you please teach me how to use MHO. I am a fan of the Monster Hunter saga and a streamer on Twitch. You can find me on Twitch as "amatsuknight". I would like to help you by testing MHO. In exchange I can advertise it if you like on my live broadcasts.

By the way. If you speak Spanish, let me know because it is my native language.

**Comment by sebastian-heinz** [comment]
At the moment this is just a walking simulator, and requires more effort. It is organized in Discord https://discord.gg/VXzXJqJySU please have a look there. If things are in a playable state documentation on how to run can be made more clear
